### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by sunstarchan** [TonyXuQAQ/iCurb#1]
It seems great work. 

But when will you release the source code? 

Do you refer to Uber's paper? **Convolutional recurrent network for road boundary extraction** https://arxiv.org/abs/2012.12160
From the demo video, it looks like the same thing you do with Uber team.

I have no access to IEEE, so where can I download your paper? I'm eager to look into it.

**Comment by TonyXuQAQ** [comment]
@sunstarchan 
The paper of iCurb could be accessed here [iCurb arxiv](https://arxiv.org/abs/2103.17118).

Because it takes a lot of effort to prepare a dataset, we plan to release the code of iCurb as a baseline in our new road-boundary detection benchmark dataset named _Topo-boundary._ You can find the paper on this dataset here [Topo-Boundary benchmark dataset](https://arxiv.org/abs/2103.17119). 

Yes, ConvBoundary is a nice work for boundary detection and it was cited in both iCurb and Topo-boundary. It was analyzed as one baseline solution in Topo-boundary, but not compared in iCurb due to limited time. In Topo-boundary, ConvBoundary is implemented by ourselves since Uber did not publish either their dataset or code, and we are still working on improving the performance of our implementation, so the comparative results in [Topo-Boundary benchmark dataset](https://arxiv.org/abs/2103.17119) are just for reference at this stage.

**Comment by sunstarchan** [comment]
@TonyXuQAQ 
Thanks for your reply. Glad to know your new work about _Topo-boundary_. Looking forward to seeing your dataset and code.
